Class {
	#name : #MenuComponent,
	#superclass : #Object,
	#category : #Restaurant
}

{ #category : #printing }
MenuComponent >> add: aMenuComponent [
	self error: 'illegal call with add. Bad.'
]

{ #category : #printing }
MenuComponent >> getChild: anInt [
	self error: 'illegal call with getChild. Bad.'
]

{ #category : #private }
MenuComponent >> getDescription [ 
	self error: 'illegal call on getDescription. Bad.'
]

{ #category : #private }
MenuComponent >> getName [
	self error: 'illegal call on getName. Bad.'
]

{ #category : #private }
MenuComponent >> getPrice [ 
	self error: 'illegal call with getPrice. Bad.'
]

{ #category : #private }
MenuComponent >> isPerhapsRaw [ 
	self error: 'illegal call with isPerhapsRaw. Bad.'
]

{ #category : #private }
MenuComponent >> isVegetarian [ 
	self error: 'illegal callisVegetarian. Bad.'
]

{ #category : #printing }
MenuComponent >> print [
	self error: 'illegal call with print. Bad.'
]

{ #category : #printing }
MenuComponent >> remove: aMenuComponent [
	self error: 'illegal call with remove. Bad.'
]
